/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.4
 * Generated at: 2025-11-02 16:30:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"UTF-8\" />\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n");
      out.write("  <title>Animated Registration Form</title>\r\n");
      out.write("  <style>\r\n");
      out.write("    * {\r\n");
      out.write("      margin: 0;\r\n");
      out.write("      padding: 0;\r\n");
      out.write("      box-sizing: border-box;\r\n");
      out.write("      font-family: \"Poppins\", sans-serif;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    body {\r\n");
      out.write("      min-height: 100vh;\r\n");
      out.write("      display: flex;\r\n");
      out.write("      justify-content: center;\r\n");
      out.write("      align-items: center;\r\n");
      out.write("      background: linear-gradient(135deg, #8e2de2, #4a00e0);\r\n");
      out.write("      padding: 20px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .form-container {\r\n");
      out.write("      width: 100%;\r\n");
      out.write("      max-width: 450px;\r\n");
      out.write("      padding: 40px 35px;\r\n");
      out.write("      border-radius: 20px;\r\n");
      out.write("      background: rgba(255, 255, 255, 0.15);\r\n");
      out.write("      backdrop-filter: blur(20px);\r\n");
      out.write("      border: 1px solid rgba(255, 255, 255, 0.3);\r\n");
      out.write("      box-shadow: 0 10px 40px rgba(0, 0, 0, 0.3);\r\n");
      out.write("      color: #fff;\r\n");
      out.write("      animation: fadeIn 1.2s ease;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    @keyframes fadeIn {\r\n");
      out.write("      from {opacity:0; transform: translateY(-40px);}\r\n");
      out.write("      to {opacity:1; transform: translateY(0);}\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    h2 { text-align:center; margin-bottom:25px; font-size:28px; color:#fff; }\r\n");
      out.write("\r\n");
      out.write("    .form-group {\r\n");
      out.write("      position: relative;\r\n");
      out.write("      margin-bottom: 25px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .form-group input,\r\n");
      out.write("    .form-group textarea,\r\n");
      out.write("    .form-group select {\r\n");
      out.write("      width: 100%;\r\n");
      out.write("      padding: 12px 15px;\r\n");
      out.write("      border: none;\r\n");
      out.write("      outline: none;\r\n");
      out.write("      border-radius: 10px;\r\n");
      out.write("      background: rgba(255, 255, 255, 0.1);\r\n");
      out.write("      color: #fff;\r\n");
      out.write("      font-size: 15px;\r\n");
      out.write("      resize: none;\r\n");
      out.write("      transition: all 0.4s ease;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .form-group label {\r\n");
      out.write("      position: absolute;\r\n");
      out.write("      top: 12px;\r\n");
      out.write("      left: 15px;\r\n");
      out.write("      color: rgba(255,255,255,0.8);\r\n");
      out.write("      font-size: 14px;\r\n");
      out.write("      pointer-events: none;\r\n");
      out.write("      transition: 0.3s ease;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .form-group input:focus + label,\r\n");
      out.write("    .form-group input:valid + label,\r\n");
      out.write("    .form-group textarea:focus + label,\r\n");
      out.write("    .form-group textarea:valid + label,\r\n");
      out.write("    .form-group select:focus + label,\r\n");
      out.write("    .form-group select:valid + label {\r\n");
      out.write("      top: -10px;\r\n");
      out.write("      left: 10px;\r\n");
      out.write("      font-size: 12px;\r\n");
      out.write("      color: #00e6ff;\r\n");
      out.write("      background: rgba(0,0,0,0.3);\r\n");
      out.write("      padding: 2px 6px;\r\n");
      out.write("      border-radius: 6px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .form-group input:focus,\r\n");
      out.write("    .form-group textarea:focus,\r\n");
      out.write("    .form-group select:focus {\r\n");
      out.write("      background: rgba(255, 255, 255, 0.2);\r\n");
      out.write("      box-shadow: 0 0 10px #00e6ff;\r\n");
      out.write("      transform: scale(1.03);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .gender-group label { font-size: 15px; margin-bottom: 8px; display:block; color: rgba(255,255,255,0.9); }\r\n");
      out.write("    .gender-options { display:flex; justify-content: space-between; flex-wrap: wrap; }\r\n");
      out.write("    .gender-options label { display:flex; align-items:center; cursor:pointer; font-size:14px; }\r\n");
      out.write("    .gender-options input { appearance:none; width:16px; height:16px; border:2px solid #00e6ff; border-radius:50%; margin-right:8px; transition:all 0.3s ease; }\r\n");
      out.write("    .gender-options input:checked { background:#00e6ff; box-shadow:0 0 10px #00e6ff; }\r\n");
      out.write("\r\n");
      out.write("    .btn {\r\n");
      out.write("      width:100%; padding:12px; border:none; border-radius:10px; font-size:16px; font-weight:600;\r\n");
      out.write("      color:#fff; background: linear-gradient(135deg,#00c6ff,#0072ff); cursor:pointer; position:relative; overflow:hidden; transition: all 0.4s ease;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .btn::before {\r\n");
      out.write("      content:\"\"; position:absolute; top:0; left:-100%; width:100%; height:100%;\r\n");
      out.write("      background: linear-gradient(120deg, transparent, rgba(255,255,255,0.6), transparent);\r\n");
      out.write("      transition: all 0.6s ease;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .btn:hover::before { left:100%; }\r\n");
      out.write("    .btn:hover { box-shadow:0 0 20px rgba(0,198,255,0.6); transform: translateY(-3px); }\r\n");
      out.write("    .btn:active { transform: scale(0.97); }\r\n");
      out.write("\r\n");
      out.write("    .form-footer { text-align:center; margin-top:20px; font-size:14px; }\r\n");
      out.write("    .form-footer a { color:#00e6ff; text-decoration:none; }\r\n");
      out.write("    .form-footer a:hover { text-decoration:underline; }\r\n");
      out.write("\r\n");
      out.write("    @media(max-width:480px){\r\n");
      out.write("      .form-container{ padding:30px 20px; }\r\n");
      out.write("      h2{ font-size:24px; }\r\n");
      out.write("      .gender-options{ flex-direction: column; gap: 8px; }\r\n");
      out.write("    }\r\n");
      out.write("  </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("  <div class=\"form-container\">\r\n");
      out.write("    <h2>Registration Form</h2>\r\n");
      out.write("	    ");

	    String msg = (String) request.getAttribute("msg");
	    if(msg != null) {
	
      out.write("\r\n");
      out.write("	<script>\r\n");
      out.write("	    alert(\"");
      out.print( msg.replace("\"","\\\"") );
      out.write("\");\r\n");
      out.write("	</script>\r\n");
      out.write("	");

	    }
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <form name=\"frm\" method=\"post\" action=\"EmployeeController\">\r\n");
      out.write("      \r\n");
      out.write("      <!-- Example text input -->\r\n");
      out.write("      <div class=\"form-group\">\r\n");
      out.write("        <input type=\"text\" name=\"f1\" required />\r\n");
      out.write("        <label>First Name</label>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"form-group\">\r\n");
      out.write("        <input type=\"text\" name=\"l1\" required />\r\n");
      out.write("        <label>Last Name</label>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <!-- Gender -->\r\n");
      out.write("      <div class=\"gender-group\">\r\n");
      out.write("        <label>Gender</label>\r\n");
      out.write("        <div class=\"gender-options\">\r\n");
      out.write("          <label><input type=\"radio\" name=\"gender\" value=\"male\" required /> Male</label>\r\n");
      out.write("          <label><input type=\"radio\" name=\"gender\" value=\"female\" required /> Female</label>\r\n");
      out.write("          <label><input type=\"radio\" name=\"gender\" value=\"other\" required /> Other</label>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <!-- Email -->\r\n");
      out.write("      <div class=\"form-group\">\r\n");
      out.write("        <input type=\"email\" name=\"e1\" required />\r\n");
      out.write("        <label>Email</label>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <!-- Mobile -->\r\n");
      out.write("      <div class=\"form-group\">\r\n");
      out.write("        <input type=\"text\" name=\"m1\" required />\r\n");
      out.write("        <label>Mobile</label>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <!-- City & State -->\r\n");
      out.write("      <div class=\"form-group\">\r\n");
      out.write("        <input type=\"text\" name=\"c1\" required />\r\n");
      out.write("        <label>City</label>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"form-group\">\r\n");
      out.write("        <input type=\"text\" name=\"s1\" required />\r\n");
      out.write("        <label>State</label>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <!-- Address -->\r\n");
      out.write("      <div class=\"form-group\">\r\n");
      out.write("        <textarea name=\"a1\" rows=\"3\" required></textarea>\r\n");
      out.write("        <label>Address</label>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <button type=\"submit\"  name=\"action\" class=\"btn\" value=\"Insert\">Registration</button>\r\n");
      out.write("    </form>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"form-footer\">\r\n");
      out.write("       <a href=\"show.jsp\">Display Employee Data</a>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
