/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.4
 * Generated at: 2025-11-02 15:59:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import com.dao.EmployeeDao;
import com.bean.Employee;
import java.util.List;

public final class show_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(4);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.dao.EmployeeDao");
    _jspx_imports_classes.add("com.bean.Employee");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Employee Records</title>\r\n");
      out.write("\r\n");
      out.write("<!-- Font Awesome for Icons -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css\">\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("/* ====== Global Styles ====== */\r\n");
      out.write("body {\r\n");
      out.write("    font-family: 'Poppins', sans-serif;\r\n");
      out.write("    background: linear-gradient(135deg, #667eea, #764ba2);\r\n");
      out.write("    margin: 0;\r\n");
      out.write("    padding: 20px;\r\n");
      out.write("    color: #333;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* ====== Page Title ====== */\r\n");
      out.write("h2 {\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    color: #fff;\r\n");
      out.write("    font-weight: 600;\r\n");
      out.write("    letter-spacing: 1px;\r\n");
      out.write("    margin-bottom: 25px;\r\n");
      out.write("    animation: fadeIn 1s ease-in-out;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* ====== Table Container ====== */\r\n");
      out.write(".table-container {\r\n");
      out.write("    overflow-x: auto;\r\n");
      out.write("    background-color: #fff;\r\n");
      out.write("    border-radius: 12px;\r\n");
      out.write("    padding: 15px;\r\n");
      out.write("    box-shadow: 0 6px 20px rgba(0,0,0,0.15);\r\n");
      out.write("    animation: slideUp 0.8s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* ====== Table Styles ====== */\r\n");
      out.write("table {\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    border-collapse: collapse;\r\n");
      out.write("    min-width: 900px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("th, td {\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    padding: 12px 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("th {\r\n");
      out.write("    background: linear-gradient(135deg, #5563de, #7c84f5);\r\n");
      out.write("    color: white;\r\n");
      out.write("    text-transform: uppercase;\r\n");
      out.write("    font-size: 14px;\r\n");
      out.write("    letter-spacing: 0.5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("td {\r\n");
      out.write("    background-color: #fff;\r\n");
      out.write("    color: #333;\r\n");
      out.write("    border-bottom: 1px solid #e8e8e8;\r\n");
      out.write("    transition: background-color 0.3s ease, transform 0.3s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("tr:hover td {\r\n");
      out.write("    background-color: #f3f4ff;\r\n");
      out.write("    transform: scale(1.01);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* ====== Button Styles ====== */\r\n");
      out.write(".btn {\r\n");
      out.write("    border: none;\r\n");
      out.write("    padding: 8px 14px;\r\n");
      out.write("    border-radius: 8px;\r\n");
      out.write("    font-size: 14px;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("    color: white;\r\n");
      out.write("    display: flex;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("    justify-content: center;\r\n");
      out.write("    gap: 6px;\r\n");
      out.write("    transition: all 0.3s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Edit Button */\r\n");
      out.write(".btn-edit {\r\n");
      out.write("    background: linear-gradient(135deg, #00c6ff, #0072ff);\r\n");
      out.write("}\r\n");
      out.write(".btn-edit:hover {\r\n");
      out.write("    transform: translateY(-3px);\r\n");
      out.write("    box-shadow: 0 4px 12px rgba(0,114,255,0.4);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Delete Button */\r\n");
      out.write(".btn-delete {\r\n");
      out.write("    background: linear-gradient(135deg, #ff416c, #ff4b2b);\r\n");
      out.write("}\r\n");
      out.write(".btn-delete:hover {\r\n");
      out.write("    transform: translateY(-3px);\r\n");
      out.write("    box-shadow: 0 4px 12px rgba(255,65,108,0.4);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Icon animations on hover */\r\n");
      out.write(".btn i {\r\n");
      out.write("    transition: transform 0.3s ease;\r\n");
      out.write("}\r\n");
      out.write(".btn:hover i {\r\n");
      out.write("    transform: rotate(15deg) scale(1.1);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* ====== Animations ====== */\r\n");
      out.write("@keyframes fadeIn {\r\n");
      out.write("    from {opacity: 0;}\r\n");
      out.write("    to {opacity: 1;}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@keyframes slideUp {\r\n");
      out.write("    from {opacity: 0; transform: translateY(20px);}\r\n");
      out.write("    to {opacity: 1; transform: translateY(0);}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* ====== Responsive Design ====== */\r\n");
      out.write("@media (max-width: 768px) {\r\n");
      out.write("    th, td {\r\n");
      out.write("        padding: 10px 6px;\r\n");
      out.write("        font-size: 13px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .btn {\r\n");
      out.write("        font-size: 12px;\r\n");
      out.write("        padding: 6px 10px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    h2 {\r\n");
      out.write("        font-size: 20px;\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@media (max-width: 600px) {\r\n");
      out.write("    table {\r\n");
      out.write("        min-width: unset;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    td, th {\r\n");
      out.write("        display: block;\r\n");
      out.write("        text-align: right;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    tr {\r\n");
      out.write("        display: block;\r\n");
      out.write("        margin-bottom: 15px;\r\n");
      out.write("        border-bottom: 2px solid #ddd;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    th {\r\n");
      out.write("        background-color: transparent;\r\n");
      out.write("        color: #5563de;\r\n");
      out.write("        text-align: left;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    td::before {\r\n");
      out.write("        content: attr(data-label);\r\n");
      out.write("        float: left;\r\n");
      out.write("        font-weight: bold;\r\n");
      out.write("        color: #444;\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<h2>Employee Records</h2>\r\n");
      out.write("\r\n");
      out.write("<div class=\"table-container\">\r\n");
      out.write("<table>\r\n");
      out.write("    <tr>\r\n");
      out.write("        <th>EMP_ID</th>\r\n");
      out.write("        <th>FNAME</th>\r\n");
      out.write("        <th>LNAME</th>\r\n");
      out.write("        <th>GENDER</th>\r\n");
      out.write("        <th>EMAIL</th>\r\n");
      out.write("        <th>MOBILE</th>\r\n");
      out.write("        <th>ADDRESS</th>\r\n");
      out.write("        <th>CITY</th>\r\n");
      out.write("        <th>STATE</th>\r\n");
      out.write("        <th>Edit</th>\r\n");
      out.write("        <th>Delete</th>\r\n");
      out.write("    </tr>\r\n");
      out.write("    ");

        List<Employee> list = EmployeeDao.getEmployees();
        for(Employee s : list) {
    
      out.write("\r\n");
      out.write("    <tr>\r\n");
      out.write("        <td data-label=\"EMP_ID\">");
      out.print(s.getEmp_id() );
      out.write("</td>\r\n");
      out.write("        <td data-label=\"FNAME\">");
      out.print(s.getFname() );
      out.write("</td>\r\n");
      out.write("        <td data-label=\"LNAME\">");
      out.print(s.getLname() );
      out.write("</td>\r\n");
      out.write("        <td data-label=\"GENDER\">");
      out.print(s.getGender() );
      out.write("</td>\r\n");
      out.write("        <td data-label=\"EMAIL\">");
      out.print(s.getEmail() );
      out.write("</td>\r\n");
      out.write("        <td data-label=\"MOBILE\">");
      out.print(s.getMobile() );
      out.write("</td>\r\n");
      out.write("        <td data-label=\"ADDRESS\">");
      out.print(s.getAddress() );
      out.write("</td>\r\n");
      out.write("        <td data-label=\"CITY\">");
      out.print(s.getCity());
      out.write("</td>\r\n");
      out.write("        <td data-label=\"STATE\">");
      out.print(s.getState() );
      out.write("</td>\r\n");
      out.write("        <td data-label=\"Edit\">\r\n");
      out.write("            <form action=\"EmployeeController\" method=\"post\">\r\n");
      out.write("                <input type=\"hidden\" name=\"emp_id\" value=\"");
      out.print(s.getEmp_id());
      out.write("\" />\r\n");
      out.write("                <button type=\"submit\" name=\"action\" value=\"Edit\" class=\"btn btn-edit\">\r\n");
      out.write("                    <i class=\"fa-solid fa-pen-to-square\"></i> Edit\r\n");
      out.write("                </button>\r\n");
      out.write("            </form>\r\n");
      out.write("        </td>\r\n");
      out.write("        <td data-label=\"Delete\">\r\n");
      out.write("            <form action=\"EmployeeController\" method=\"post\">\r\n");
      out.write("                <input type=\"hidden\" name=\"emp_id\" value=\"");
      out.print(s.getEmp_id());
      out.write("\" />\r\n");
      out.write("                <button type=\"submit\" name=\"action\" value=\"Delete\" class=\"btn btn-delete\">\r\n");
      out.write("                    <i class=\"fa-solid fa-trash-can\"></i> Delete\r\n");
      out.write("                </button>\r\n");
      out.write("            </form>\r\n");
      out.write("        </td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    ");
 } 
      out.write("\r\n");
      out.write("</table>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
