/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.4
 * Generated at: 2026-02-07 07:11:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import com.bean.Student;

public final class update_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("com.bean.Student");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\" />\r\n");
      out.write("<title>Student Update Form</title>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/style.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	<div class=\"form-container\">\r\n");
      out.write("		<b style=\"color:green\">\r\n");
      out.write("    ");

    	Student s = (Student)request.getAttribute("s");
        if(request.getAttribute("msg")!=null)
        {
        	out.println(request.getAttribute("msg"));
        }
    
      out.write("\r\n");
      out.write("    </b>\r\n");
      out.write("		\r\n");
      out.write("		</b>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"title\">\r\n");
      out.write("			<i class=\"fa-solid fa-user-astronaut\"></i> Student Update Form\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<!-- Profile Upload -->\r\n");
      out.write("		<div class=\"profile-upload\">\r\n");
      out.write("			<label class=\"profile-box\"> <img id=\"preview\"\r\n");
      out.write("				src=\"https://cdn-icons-png.flaticon.com/512/149/149071.png\" />\r\n");
      out.write("				<div class=\"upload-text\">Select Photo</div> <input type=\"file\"\r\n");
      out.write("				accept=\"image/*\" hidden onchange=\"loadImage(event)\">\r\n");
      out.write("			</label>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<form name=\"frm\" method=\"post\" action=\"StudentController\">\r\n");
      out.write("\r\n");
      out.write("			<input type=\"hidden\" name=\"sid\" value=\"");
      out.print(s.getSid());
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("			<div class=\"form-grid\">\r\n");
      out.write("\r\n");
      out.write("				<div class=\"input-group\">\r\n");
      out.write("					<i class=\"fa fa-user\"></i> <input type=\"text\" name=\"fname\"\r\n");
      out.write("						value=\"");
      out.print(s.getFname());
      out.write("\" placeholder=\"First Name\">\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"input-group\">\r\n");
      out.write("					<i class=\"fa fa-user\"></i> <input type=\"text\" name=\"lname\"\r\n");
      out.write("						value=\"");
      out.print(s.getLname());
      out.write("\" placeholder=\"Last Name\">\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"input-group\">\r\n");
      out.write("					<i class=\"fa fa-phone\"></i> <input type=\"text\" name=\"mobile\"\r\n");
      out.write("						value=\"");
      out.print(s.getMobile());
      out.write("\" placeholder=\"Mobile\">\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"input-group\">\r\n");
      out.write("					<i class=\"fa fa-envelope\"></i> <input type=\"email\" name=\"email\"\r\n");
      out.write("						value=\"");
      out.print(s.getEmail());
      out.write("\" placeholder=\"Email\">\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"input-group\">\r\n");
      out.write("					<i class=\"fa fa-lock\"></i> <input type=\"password\" name=\"password\"\r\n");
      out.write("						value=\"");
      out.print(s.getPassword());
      out.write("\" placeholder=\"Password\">\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"input-group\">\r\n");
      out.write("					<i class=\"fa fa-graduation-cap\"></i> <input type=\"text\"\r\n");
      out.write("						name=\"education\" value=\"");
      out.print(s.getEducation());
      out.write("\"\r\n");
      out.write("						placeholder=\"Education\">\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"input-group\">\r\n");
      out.write("					<i class=\"fa fa-venus-mars\"></i> <select name=\"gender\">\r\n");
      out.write("						<option value=\"Male\"\r\n");
      out.write("							");
      out.print("Male".equals(s.getGender()) ? "selected" : "");
      out.write(">\r\n");
      out.write("							Male</option>\r\n");
      out.write("\r\n");
      out.write("						<option value=\"Female\"\r\n");
      out.write("							");
      out.print("Female".equals(s.getGender()) ? "selected" : "");
      out.write(">\r\n");
      out.write("							Female</option>\r\n");
      out.write("\r\n");
      out.write("						<option value=\"Other\"\r\n");
      out.write("							");
      out.print("Other".equals(s.getGender()) ? "selected" : "");
      out.write(">\r\n");
      out.write("							Other</option>\r\n");
      out.write("					</select>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"input-group\">\r\n");
      out.write("					<i class=\"fa fa-globe\"></i> <input type=\"text\" name=\"religion\"\r\n");
      out.write("						value=\"");
      out.print(s.getReligion());
      out.write("\" placeholder=\"Religion\">\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"input-group\">\r\n");
      out.write("					<i class=\"fa fa-layer-group\"></i> <input type=\"text\"\r\n");
      out.write("						name=\"category\" value=\"");
      out.print(s.getCategory());
      out.write("\"\r\n");
      out.write("						placeholder=\"Category\">\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"input-group full\">\r\n");
      out.write("					<i class=\"fa fa-home\"></i> <input type=\"text\" name=\"address\"\r\n");
      out.write("						value=\"");
      out.print(s.getAddress());
      out.write("\" placeholder=\"Address\">\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"input-group\">\r\n");
      out.write("					<i class=\"fa fa-city\"></i> <input type=\"text\" name=\"city\"\r\n");
      out.write("						value=\"");
      out.print(s.getCity());
      out.write("\" placeholder=\"City\">\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"input-group\">\r\n");
      out.write("					<i class=\"fa fa-map-pin\"></i> <input type=\"text\" name=\"zipcode\"\r\n");
      out.write("						value=\"");
      out.print(s.getZipcode());
      out.write("\" placeholder=\"Zipcode\">\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"input-group\">\r\n");
      out.write("					<i class=\"fa fa-building\"></i> <input type=\"text\" name=\"district\"\r\n");
      out.write("						value=\"");
      out.print(s.getDistrict());
      out.write("\" placeholder=\"District\">\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"input-group\">\r\n");
      out.write("					<i class=\"fa fa-flag\"></i> <input type=\"text\" name=\"state\"\r\n");
      out.write("						value=\"");
      out.print(s.getState());
      out.write("\" placeholder=\"State\">\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<button class=\"btn\" name=\"action\" value=\"update\">Update\r\n");
      out.write("				Student</button>\r\n");
      out.write("\r\n");
      out.write("		</form>\r\n");
      out.write("		```\r\n");
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<script>\r\n");
      out.write("		function loadImage(event) {\r\n");
      out.write("			const preview = document.getElementById('preview');\r\n");
      out.write("			preview.src = URL.createObjectURL(event.target.files[0]);\r\n");
      out.write("		}\r\n");
      out.write("	</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
