/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.4
 * Generated at: 2026-02-07 08:26:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import com.dao.StudentDao;
import com.bean.Student;
import java.util.List;

public final class view_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(4);
    _jspx_imports_classes.add("com.bean.Student");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.dao.StudentDao");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Student Table</title>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/view.css\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div class=\"table-container\">\r\n");
      out.write("\r\n");
      out.write("<div class=\"title\">\r\n");
      out.write("<i class=\"fa-solid fa-database\"></i>\r\n");
      out.write("Student Master Record\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<table>\r\n");
      out.write("\r\n");
      out.write("<thead>\r\n");
      out.write("<tr>\r\n");
      out.write("<th><i class=\"fa fa-id-card icon\"></i>SID</th>\r\n");
      out.write("<th><i class=\"fa fa-user icon\"></i>Photo</th>\r\n");
      out.write("<th><i class=\"fa fa-user icon\"></i>First</th>\r\n");
      out.write("<th><i class=\"fa fa-user icon\"></i>Last</th>\r\n");
      out.write("<th><i class=\"fa fa-phone icon\"></i>Mobile</th>\r\n");
      out.write("<th><i class=\"fa fa-envelope icon\"></i>Email</th>\r\n");
      out.write("<th><i class=\"fa fa-lock icon\"></i>Password</th>\r\n");
      out.write("<th><i class=\"fa fa-graduation-cap icon\"></i>Education</th>\r\n");
      out.write("<th><i class=\"fa fa-venus-mars icon\"></i>Gender</th>\r\n");
      out.write("<th><i class=\"fa fa-om icon\"></i>Religion</th>\r\n");
      out.write("<th><i class=\"fa fa-layer-group icon\"></i>Category</th>\r\n");
      out.write("<th><i class=\"fa fa-location-dot icon\"></i>Address</th>\r\n");
      out.write("<th><i class=\"fa fa-city icon\"></i>City</th>\r\n");
      out.write("<th><i class=\"fa fa-mail-bulk icon\"></i>Zipcode</th>\r\n");
      out.write("<th><i class=\"fa fa-map icon\"></i>District</th>\r\n");
      out.write("<th><i class=\"fa fa-flag icon\"></i>State</th>\r\n");
      out.write("<th>Edit</th>\r\n");
      out.write("<th>Delete</th>\r\n");
      out.write("</tr>\r\n");
      out.write("</thead>\r\n");
      out.write("\r\n");
      out.write("<tbody>\r\n");

	List<Student> list = StudentDao.getAllStudent();
   		for(Student s:list)
   		{

      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("<td>");
      out.print(s.getSid() );
      out.write("</td>\r\n");
      out.write("<td>\r\n");
      out.write("		<img alt=\"\" src=\"profile_picture/");
      out.print( s.getPrifile_pictute());
      out.write("\" style=\"width:50px; height:50px;\">\r\n");
      out.write("		\r\n");
      out.write("</td>\r\n");
      out.write("<td>");
      out.print(s.getFname() );
      out.write("</td>\r\n");
      out.write("<td>");
      out.print(s.getLname());
      out.write("</td>\r\n");
      out.write("<td>");
      out.print(s.getMobile() );
      out.write("</td>\r\n");
      out.write("<td>");
      out.print(s.getEmail() );
      out.write("</td>\r\n");
      out.write("<td>");
      out.print(s.getPassword());
      out.write("</td>\r\n");
      out.write("<td>");
      out.print(s.getEducation() );
      out.write("</td>\r\n");
      out.write("<td>");
      out.print(s.getGender() );
      out.write("</td>\r\n");
      out.write("<td>");
      out.print(s.getReligion() );
      out.write("</td>\r\n");
      out.write("<td>");
      out.print(s.getCategory() );
      out.write("</td>\r\n");
      out.write("<td>");
      out.print(s.getAddress() );
      out.write("</td>\r\n");
      out.write("<td>");
      out.print(s.getCity() );
      out.write("</td>\r\n");
      out.write("<td>");
      out.print(s.getZipcode() );
      out.write("</td>\r\n");
      out.write("<td>");
      out.print(s.getDistrict());
      out.write("</td>\r\n");
      out.write("<td>");
      out.print(s.getState() );
      out.write("</td>\r\n");
      out.write("\r\n");
      out.write("<td>\r\n");
      out.write("<form action=\"StudentController\" method=\"post\">\r\n");
      out.write("<input type=\"hidden\" name=\"sid\" value=\"");
      out.print( s.getSid() );
      out.write("\">\r\n");
      out.write("<button class=\"btn edit\" name=\"action\" value=\"edit\">\r\n");
      out.write("<i class=\"fa fa-pen\"></i> Edit\r\n");
      out.write("</button>\r\n");
      out.write("</form>\r\n");
      out.write("</td>\r\n");
      out.write("<td>\r\n");
      out.write("<form method=\"post\" action=\"StudentController\">\r\n");
      out.write("<input type=\"hidden\" name=\"sid\" value=\"");
      out.print( s.getSid() );
      out.write("\">\r\n");
      out.write("<button class=\"btn delete\" name=\"action\" value=\"delete\">\r\n");
      out.write("<i class=\"fa fa-trash\"></i> Delete\r\n");
      out.write("</button>\r\n");
      out.write("</form>\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
 
   		}

      out.write("\r\n");
      out.write("</tbody>\r\n");
      out.write("\r\n");
      out.write("</table>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("    ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
