/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.4
 * Generated at: 2025-12-25 08:34:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import com.bean.Drivers;
import com.dao.DriversDao;
import com.bean.DriverView;

public final class update_002ddrivers_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/header.jsp", Long.valueOf(1766601659606L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(4);
    _jspx_imports_classes.add("com.bean.DriverView");
    _jspx_imports_classes.add("com.bean.Drivers");
    _jspx_imports_classes.add("com.dao.DriversDao");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Ultra AI Logistics</title>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("\r\n");
      out.write("<!-- FONT & ICONS -->\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;600;700&display=swap\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/index.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!-- ================= NAVBAR ================= -->\r\n");
      out.write("	<nav class=\"navbar\">\r\n");
      out.write("		<div class=\"logo\">\r\n");
      out.write("			<span>Admin Dashboard</span>-Logistics\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"menu-toggle\" id=\"menuToggle\">\r\n");
      out.write("			<span></span><span></span><span></span>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<ul class=\"menu\" id=\"menu\">\r\n");
      out.write("			<li class=\"menu-item\"><a href=\"admin-index.jsp\">Dashboard</a></li>\r\n");
      out.write("\r\n");
      out.write("			<li class=\"menu-item\"><a href=\"#\">Routes</a>\r\n");
      out.write("				<ul class=\"dropdown\">\r\n");
      out.write("					<li><a href=\"#\">Add Route</a></li>\r\n");
      out.write("					<li><a href=\"#\">View Route </a></li>\r\n");
      out.write("				</ul></li>\r\n");
      out.write("			<li class=\"menu-item\"><a href=\"#\">Service</a>\r\n");
      out.write("				<ul class=\"dropdown\">\r\n");
      out.write("					<li><a href=\"add-driver.jsp\">Add Driver</a></li>\r\n");
      out.write("					<li><a href=\"#\">Add Vehicle</a></li>\r\n");
      out.write("					<li><a href=\"#\">Add Vehicle Feul</a></li>\r\n");
      out.write("					<li><a href=\"#\">Add Maintanance</a></li>\r\n");
      out.write("				</ul></li>\r\n");
      out.write("\r\n");
      out.write("			\r\n");
      out.write("			<li class=\"menu-item\"><a href=\"#\">Views</a>\r\n");
      out.write("				<ul class=\"dropdown\">\r\n");
      out.write("					<li><a href=\"view-drivers.jsp\">View Drivers</a></li>\r\n");
      out.write("					<li><a href=\"#\">View Vehicles</a></li>\r\n");
      out.write("					<li><a href=\"#\">View Feuls</a></li>\r\n");
      out.write("				</ul></li>\r\n");
      out.write("				<li class=\"menu-item\"><a href=\"#\">Assign</a>\r\n");
      out.write("				<ul class=\"dropdown\">\r\n");
      out.write("					<li><a href=\"#\"> Add Vehicle-Driver</a></li>\r\n");
      out.write("					<li><a href=\"#\">View Vehicles-Driver</a></li>\r\n");
      out.write("					\r\n");
      out.write("				</ul></li>\r\n");
      out.write("			<li class=\"menu-item\"><a href=\"#\">Report</a>\r\n");
      out.write("				<ul class=\"dropdown\">\r\n");
      out.write("					<li><a href=\"#\">Incident Report</a></li>\r\n");
      out.write("					<li><a href=\"#\">Other Report</a></li>\r\n");
      out.write("				</ul></li>\r\n");
      out.write("			<li class=\"menu-item\"><a href=\"#\">Contact</a>\r\n");
      out.write("				<ul class=\"dropdown\">\r\n");
      out.write("					<li><a href=\"#\">Support</a></li>\r\n");
      out.write("					<li><a href=\"#\">Email</a></li>\r\n");
      out.write("				</ul></li>\r\n");
      out.write("		</ul>\r\n");
      out.write("	</nav>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Edit Driver Details</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<section class=\"form-section\">\r\n");
      out.write("		<div class=\"form-wrapper\">\r\n");
      out.write("\r\n");
      out.write("			<!-- LEFT INFO -->\r\n");
      out.write("			<div class=\"form-info\">\r\n");
      out.write("				<h2>Edit Driver Data</h2>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"info-box\">\r\n");
      out.write("					<i class=\"fa-solid fa-truck-fast\"></i> <span>All Vehicle\r\n");
      out.write("						Types Available</span>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"info-box\">\r\n");
      out.write("					<i class=\"fa-solid fa-location-dot\"></i> <span>Pan India\r\n");
      out.write("						Delivery Network</span>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"info-box\">\r\n");
      out.write("					<i class=\"fa-solid fa-headset\"></i> <span>24×7 Customer\r\n");
      out.write("						Support</span>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<!-- FORM -->\r\n");
      out.write("			");

			DriverView d = (DriverView) request.getAttribute("d");
			
      out.write("\r\n");
      out.write("			<form class=\"form-box\" name=\"frm\" method=\"post\"\r\n");
      out.write("				action=\"DriverController\">\r\n");
      out.write("				<div class=\"input-group\">\r\n");
      out.write("					<input type=\"hidden\" name=\"user_id\" value=\"");
      out.print(d.getUser_id());
      out.write("\"\r\n");
      out.write("						required>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"input-group\">\r\n");
      out.write("					<i class=\"fa-solid fa-user\"></i> <input type=\"text\"\r\n");
      out.write("						name=\"driver_id\" value=\"");
      out.print(d.getDriver_id());
      out.write("\"\r\n");
      out.write("						placeholder=\"Driver Id\" readonly=\"readonly\" required>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"input-group\">\r\n");
      out.write("					<i class=\"fa-solid fa-user\"></i> <input type=\"text\" name=\"name\"\r\n");
      out.write("						value=\"");
      out.print(d.getName());
      out.write("\" placeholder=\"Full Name\" required>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"input-group\">\r\n");
      out.write("					<i class=\"fa-solid fa-envelope\"></i> <input type=\"email\"\r\n");
      out.write("						name=\"email\" value=\"");
      out.print(d.getEmail());
      out.write("\" placeholder=\"Email Address\"\r\n");
      out.write("						required>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"input-group\">\r\n");
      out.write("					<i class=\"fa fa-lock\"></i> <input type=\"password\" name=\"password\"\r\n");
      out.write("						value=\"");
      out.print(d.getPassword());
      out.write("\" placeholder=\"Password\" required>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"input-group\">\r\n");
      out.write("					<i class=\"fa fa-user\"></i> <input type=\"text\" name=\"username\"\r\n");
      out.write("						value=\"");
      out.print(d.getUsername());
      out.write("\" placeholder=\"Enter Username\" required>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"input-group\">\r\n");
      out.write("					<i class=\"fa-solid fa-phone\"></i> <input type=\"text\"\r\n");
      out.write("						name=\"phone_no\" value=\"");
      out.print(d.getPhone_no());
      out.write("\"\r\n");
      out.write("						placeholder=\"Mobile Number\" required>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"input-group\">\r\n");
      out.write("					<i class=\"fa fa-id-card\"></i> <input type=\"text\" name=\"license_no\"\r\n");
      out.write("						value=\"");
      out.print(d.getLicense_no());
      out.write("\" placeholder=\"License Number\"\r\n");
      out.write("						required>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"input-group\">\r\n");
      out.write("					<i class=\"fa-solid fa-car-side\"></i> <select name=\"role\" required>\r\n");
      out.write("						<option value=\"driver\"\r\n");
      out.write("							");
      out.print( "driver".equals(d.getRole()) ? "selected" : "" );
      out.write(">\r\n");
      out.write("							Driver</option>\r\n");
      out.write("					</select>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"input-group\">\r\n");
      out.write("					<i class=\"fa fa-check-circle\"></i> <input type=\"text\" name=\"status\"\r\n");
      out.write("						value=\"");
      out.print(d.getStatus());
      out.write("\" placeholder=\"Status\" required>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<button type=\"submit\" name=\"action\" value=\"update\">Update\r\n");
      out.write("					Driver</button>\r\n");
      out.write("			</form>\r\n");
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("	</section>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
